sudo: false
language: ruby

rvm:
  - 2.2.9

script: bundle exec rake all

cache: bundler

before_install:
  - gem update --system

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile

notifications:
  email: false

deploy:
  provider: rubygems
  gem: letter_opener_web
  api_key:
    secure: Rv1IgeIhnfIV9NVr3iPwb2UCXe0UEtuZHfgkGruu3yvfoSGmQQ0xnc45ZhOH8ANl6tjzYNuilSDYbhz3fWOmniHsnzLGbFbccz/CWHmldUpPgVnKQ0d0Bm2EeNuVpmHwdnG7KEqMC0x1gxFYks62BGpx4C/2Kh5nWbvvPxN8X0U=
  on:
    tags: true
    repo: fgrehm/letter_opener_web
