version: '2'

services:
  app:
    volumes:
      - .:/app
      - ../:/localgems
      - bundler-data:/bundle
      - ssh-data:/ssh:ro

volumes:
  bundler-data:
    external:
      name: bundler_data

  ssh-data:
    external:
      name: ssh_data
