version: '2'

services:
  app:
    image: abakpress/ruby-app:$RUBY_IMAGE_TAG
    environment:
      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
      - SSH_AUTH_SOCK=/ssh/auth/sock
      - TEST_DB_HOST=db
      - TEST_DB_NAME=docker
      - TEST_DB_USERNAME=postgres
    command: bash

